# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VivadoProject/ElectronicLock/ElectronicLock.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/ElectronicLock/ElectronicLock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProject/ElectronicLock/ElectronicLock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/sources_1/new/warning.v
  D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/sources_1/new/lock_register.v
  D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/sources_1/new/Inputer.v
  D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/sources_1/new/key_register.v
  D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/sources_1/new/elock.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/constrs_1/new/lock_constraints.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/ElectronicLock/ElectronicLock.srcs/constrs_1/new/lock_constraints.xdc]


synth_design -top elock -part xc7a35tcsg324-3


write_checkpoint -force -noxdef elock.dcp

catch { report_utilization -file elock_utilization_synth.rpt -pb elock_utilization_synth.pb }
