# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertKey',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False, verbose_name=b'Serial')),
                ('cert', models.CharField(max_length=1024, verbose_name=b'Cert PEM')),
                ('privkey', models.CharField(max_length=1024, verbose_name=b'Privkey PEM')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.CharField(max_length=64, verbose_name=b'Country Name')),
                ('ST', models.CharField(max_length=64, verbose_name=b'State or province name')),
                ('L', models.CharField(max_length=64, verbose_name=b'Locality name')),
                ('O', models.CharField(max_length=64, verbose_name=b'Organization name')),
                ('OU', models.CharField(max_length=64, verbose_name=b'Organizational unit name')),
                ('CN', models.CharField(max_length=64, verbose_name=b'Common name')),
                ('emailAddress', models.EmailField(max_length=254, verbose_name=b'Email Address')),
                ('der', models.CharField(max_length=1024, verbose_name=b'der')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
