set_property IOSTANDARD LVCMOS33 [get_ports {D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Green]
set_property IOSTANDARD LVCMOS33 [get_ports Red]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports warn_sig]
set_property PACKAGE_PIN R1 [get_ports {D[0]}]
set_property PACKAGE_PIN N4 [get_ports {D[1]}]
set_property PACKAGE_PIN M4 [get_ports {D[2]}]
set_property PACKAGE_PIN R2 [get_ports {D[3]}]
set_property PACKAGE_PIN P2 [get_ports {D[4]}]
set_property PACKAGE_PIN P3 [get_ports {D[5]}]
set_property PACKAGE_PIN P4 [get_ports {D[6]}]
set_property PACKAGE_PIN P17 [get_ports Clk]
set_property PACKAGE_PIN K1 [get_ports Green]
set_property PACKAGE_PIN K3 [get_ports Red]

set_property PACKAGE_PIN F6 [get_ports {input_light[7]}]
set_property PACKAGE_PIN G4 [get_ports {input_light[6]}]
set_property PACKAGE_PIN G3 [get_ports {input_light[5]}]
set_property PACKAGE_PIN H4 [get_ports {input_light[3]}]
set_property PACKAGE_PIN J3 [get_ports {input_light[2]}]
set_property PACKAGE_PIN J2 [get_ports {input_light[1]}]
set_property PACKAGE_PIN K2 [get_ports {input_light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_light[0]}]

set_property PACKAGE_PIN M1 [get_ports warn_sig]


set_property IOSTANDARD LVCMOS33 [get_ports Circ]
set_property PACKAGE_PIN H6 [get_ports Circ]

set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]

set_property PACKAGE_PIN H5 [get_ports {count[1]}]
set_property PACKAGE_PIN J5 [get_ports {count[0]}]
set_property PACKAGE_PIN J4 [get_ports {input_light[4]}]
set_property PACKAGE_PIN P5 [get_ports {D[7]}]
set_property PACKAGE_PIN R15 [get_ports Reset]

set_property IOSTANDARD LVCMOS33 [get_ports {countDown[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[7]}]

set_property PACKAGE_PIN D5 [get_ports {countDown[8]}]
set_property PACKAGE_PIN B2 [get_ports {countDown[7]}]
set_property PACKAGE_PIN B3 [get_ports {countDown[6]}]
set_property PACKAGE_PIN A1 [get_ports {countDown[5]}]
set_property PACKAGE_PIN B1 [get_ports {countDown[4]}]
set_property PACKAGE_PIN A3 [get_ports {countDown[3]}]
set_property PACKAGE_PIN A4 [get_ports {countDown[2]}]
set_property PACKAGE_PIN B4 [get_ports {countDown[1]}]
set_property PACKAGE_PIN G2 [get_ports {countDown[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countDown[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports Check]
set_property PACKAGE_PIN R17 [get_ports Check]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {Check_IBUF}]

